name: Check

on:
  pull_request:
  push:
    branches:
      - main
      - next

permissions:
  id-token: write # used to upload artifacts to codecov

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build
        run: pnpm build

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
