name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    if: github.repository == 'ndelangen/circleci-config-sdk-ts'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba
        with:
          publish: pnpm release
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
